const BASE_URL = process.env.REACT_APP_BASE_URL;
const API_KEY_PARAM = `?api_key=${process.env.REACT_APP_API_KEY}`;
const BACKDROP_BASE_URL = process.env.REACT_APP_BACKDROP_BASE_URL;
const SMALL_IMG_COVER_BASE_URL = process.env.REACT_APP_SMALL_IMG_COVER_BASE_URL;

export { BASE_URL, API_KEY_PARAM, BACKDROP_BASE_URL, SMALL_IMG_COVER_BASE_URL };